apiVersion: v1
kind: Namespace
metadata:
  name: filebrowser-app
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "shared-folder-data"
  namespace: filebrowser-app
spec:
  storageClassName: shared-folder
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "2Gi"
  volumeName: "shared-folder-data"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: filebrowser
  namespace: filebrowser-app
spec:
  repo: https://utkuozdemir.org/helm-charts
  chart: filebrowser
  targetNamespace: filebrowser-app
  valuesContent: |-
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 100
    rootDir:
      pvc:
        existingClaim: "shared-folder-data"
    config:
      baseURL: /filebrowser
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser-websecure
  namespace: filebrowser-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/filebrowser`)
      kind: Rule
      services:
        - name: filebrowser
          port: 80
  tls:
    secretName: host-selfsigned-cert